Repository KakizakiHayate/kuotore, pull requests merged in 2023-11, with the labels that each got.

#2 Bluetooth通信をする
  Kuotore.xcodeproj/project.pbxproj
  Kuotore/CentralViewModel.swift
  Kuotore/ContentView.swift
  Kuotore/PeripheralViewModel.swift
  Kuotore/TransferService.swift
  M5StickCPlus/sendDistance/sendDistance.ino
Labels: 実装

#3 CentralViewManagerをリファクタリング
  Kuotore.xcodeproj/project.pbxproj
  Kuotore/CentralViewManager.swift
  Kuotore/CentralViewModel.swift
  Kuotore/ContentView.swift
Labels: 修正

#10 BLEで使うサンプルコードを削除
  Kuotore.xcodeproj/project.pbxproj
  Kuotore/ContentView.swift
  Kuotore/PeripheralViewModel.swift
Labels: 修正

#15 トレーニング画面機能実装
  Kuotore.xcodeproj/project.pbxproj
  Kuotore/Models/RealmManager.swift
  Kuotore/Models/RealmObjects/Training.swift
  Kuotore/Utils/Logger.swift
  Kuotore/ViewModels/AddTrainingEvent/AddTrainingEventViewModel.swift
  Kuotore/ViewModels/Training/TrainingViewModel.swift
  Kuotore/Views/AddTrainingEvent/AddTrainingEventView.swift
  Kuotore/Views/Training/TrainingView.swift
Labels: 実装, 機能

#14 ホーム画面とトレーニング画面実装
  Kuotore.xcodeproj/project.pbxproj
  Kuotore/Assets.xcassets/Colors/AppDarkGrayColor.colorset/Contents.json
  Kuotore/Assets.xcassets/Colors/AppLightGrayColor.colorset/Contents.json
  Kuotore/Assets.xcassets/Colors/AppPrimaryColor.colorset/Contents.json
  Kuotore/Info.plist
  Kuotore/Models/RealmManager.swift
  Kuotore/Models/RealmObjects/TrainingInfo.swift
  Kuotore/Views/HomeView.swift
  Kuotore/Views/InitializeTrainingView.swift
  Kuotore/Views/TrainingView.swift
Labels: 実装, UI

#18 カスタム種目生成の情報入力画面と距離測る画面作成
  Kuotore.xcodeproj/project.pbxproj
  Kuotore/Views/AddTrainingView.swift
  Kuotore/Views/HomeView.swift
  Kuotore/Views/SetTargetDistenceView.swift
Labels: 実装, UI
